{{- if and .Values.vectorStore.enabled (eq .Values.vectorStore.type "qdrant") .Values.vectorStore.qdrant.enabled (not .Values.vectorStore.qdrant.external.enabled) .Values.vectorStore.qdrant.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bifrost.fullname" . }}-qdrant
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
    app.kubernetes.io/component: vectorstore-qdrant
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.vectorStore.qdrant.persistence.storageClass }}
  {{- if (eq "-" .Values.vectorStore.qdrant.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.vectorStore.qdrant.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.vectorStore.qdrant.persistence.size }}
{{- end }}

